/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kodyshan' at '16-8-17 下午1:12' with Gradle 2.14
 *
 * @author kodyshan, @date 16-8-17 下午1:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
